asr:
  sample_rate: 16000     # Sampling rate in Hz
  chunk: 1024            # Buffer size (if needed in future)
  channels: 1            # Mono channel
  duration: 5            # Default recording duration in seconds
  device_index: null     # Use default input device

tts:
  lang: hi               # Text-to-speech language

email:
  to_email: sanikagadade641@gmail.com  # Receiver email
  subject_prefix: "ЁЯУв P2P Lending Query"

logging:
  log_file: complaint_log.csv
  log_format: "[{timestamp}] - {query} -> {reply} | {status}"
  fallback_responses:
    - "рдорд╛рдлрд╝ рдХреАрдЬрд┐рдП, рдХреГрдкрдпрд╛ рдЕрдкрдирд╛ рдкреНрд░рд╢реНрди рдлрд┐рд░ рд╕реЗ рдХрд╣реЗрдВред"
    - "рдореИрдВ рд╕рдордЭ рдирд╣реАрдВ рдкрд╛рдпрд╛, рдХреГрдкрдпрд╛ рдФрд░ рд╕реНрдкрд╖реНрдЯ рдмреЛрд▓реЗрдВред"
    - "рдХреГрдкрдпрд╛ рдХреБрдЫ рд╕рдордп рдмрд╛рдж рдлрд┐рд░ рд╕реЗ рдкреНрд░рдпрд╛рд╕ рдХрд░реЗрдВред"

locations:
  allowed:
    - mumbai
    - pune
    - delhi
    - kolhapur
    - nashik
